### PR TITLE
Introduce mocking framework and increase coverage

### PR DESCRIPTION
**Pull request by BradleyBoutcher**
This change introduces three common Golang patterns to the SonyFlake project test framework:

- types: this will allow fine-tuned control over imported types by defining how they will be used, project-wide

- mock: this allows the generation of mock constructors, which lends itself to testing any individual path in a function by
"injecting" a mock object which matches the expected type

- array-based-testing: `privateIPv4` and `lower16BitPrivateIP` were lacking tests for their error paths,
but using types and mocks, I was able add two array-based tests that cover all test cases for these methods

This change also increases test coverage to 💯, while adding no additional time for testing ⌛ .

This is a _really_ cool project, and I'd be happy to contribute more!

### CODE REVIEW

**Comment by BradleyBoutcher** [comment]
I realized I didn't notify anyone about this PR, so I apologize for the bother, and no rush!
@yuokada @osamingo

**Comment by yuokada** [comment]
@BradleyBoutcher Sorry for late reply. 
I'm just a contributor. I don't have any responsibility or permission for this repository.

**Comment by BradleyBoutcher** [comment]
No worries! Thank you for the response!

**Comment by YoshiyukiMineo** [comment]
Thank you for your PR.

**Pull request merged**
